# fly.toml app configuration file generated for tws-ai-rough-surf-5096 on 2024-12-01T18:40:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tws-ai-rough-surf-5096'
primary_region = 'dfw'

[build]
  # Add a build command to run Prisma generate
  command = "npm install && npx prisma generate"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
